#!/usr/bin/env python3
"""Inject the Live TV search app-control into scripts/package-tizen.mjs.

config.xml is GENERATED by buildConfigXml() in scripts/package-tizen.mjs, so the
additive edit lands in the generator, not in a static config.xml. This script is
idempotent: running it twice is a no-op.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ANCHOR = '  <tizen:privilege name="http://tizen.org/privilege/tv.inputdevice"/>\n'
APP_CONTROL = (
    "  <tizen:app-control>\n"
    "    <tizen:src>\n"
    "      <tizen:action>http://tizen.org/appcontrol/operation/search</tizen:action>\n"
    "    </tizen:src>\n"
    "  </tizen:app-control>\n"
)
MARKER = "http://tizen.org/appcontrol/operation/search"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True)
    args = parser.parse_args()
    target = Path(args.root).resolve() / "scripts" / "package-tizen.mjs"
    if not target.exists():
        print(f"missing {target}", file=sys.stderr)
        return 1
    text = target.read_text(encoding="utf-8")
    if MARKER in text:
        print("app-control already present; no change")
        return 0
    if text.count(ANCHOR) != 1:
        print("anchor not found exactly once", file=sys.stderr)
        return 1
    target.write_text(text.replace(ANCHOR, APP_CONTROL + ANCHOR, 1), encoding="utf-8")
    print("injected Live TV search app-control")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
